apiVersion: apps/v1
kind: Deployment
metadata:
  name: hawes-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hawes-app
    spec:
      containers:
      - name: hawes-app
        image: hawes-app-image
        imagePullPolicy: Never
        resources:
          limits:
            memory: "1000Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10
  selector:
    matchLabels:
      app: hawes-app
---
apiVersion: v1
kind: Service
metadata:
  name: hawes-app-service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  selector:
    app: hawes-app